version: '3.8'

services:
  database:
    container_name: fablab_test_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fablab_test
      MYSQL_USER: fablab_test_user
      MYSQL_PASSWORD: fablab_test_pwd
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: fablab_test_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/fablab_test_app
    depends_on:
      - database

  nginx:
    container_name: fablab_test_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/fablab_test_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fablab_test_pma
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database
